### ISSUE TITLE
 bash: unimgc: Kommando nicht gefunden. -> How to install?

### ISSUE THREAD

**Issue by robochud** [Shizmob/unimgc#2]
Hi

I install the newest Debian 10.
I get the error "bash: unimgc: Kommando nicht gefunden."(command not found)

- git clone https://github.com/Shizmob/unimgc.git test
- cd test
- make
- unimgc

Thanks and greetings

**Comment by Qwertylex** [comment]
try `./unimgc -h` from inside of your `test` directory

**Comment by Qwertylex** [comment]
if you want to install it, i guess just copy it to `/usr/bin` or anywhere else on your `$PATH`?

**Comment by shizmob** [comment]
What @Qwertylex said is correct, although I'd recommend `/usr/local/bin` instead.
