### ISSUE TITLE
Supported on MacOS?

### ISSUE THREAD

**Issue by hashildy** [Shizmob/unimgc#3]
Is this program supported on MacOS?

**Comment by Qwertylex** [comment]
I don't have access to macOS to test
if you're running macOS just try compiling it?
it should be as easy as `make` (after downloading or `git clone`'ing the repo) assuming you have xcode and stuff installed

**Comment by shizmob** [comment]
Yes, in fact, I use it on macOS myself! As @Qwertylex mentioned, it compiles the same, you just need the Xcode command-line tools installed (`xcode-select --install`).
